name: CI Runner Test

on:
  push:
    branches:
    - main
  workflow_dispatch:
  
jobs:
 test-runner:
  runs-on: ubuntu-latest
  permissions:
      contents: write
  steps:
   - name: Checkout Code
     uses: actions/checkout@v4
     with:
        fetch-depth: 0
   - name: Print Message
     run: echo "Github Runner is working!"
