name: CI Runner Test

on:
  push:
    branches:
    - main
  workflow_dispatch:
  
jobs:
 test-runner:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Code
     run: actions/checkout@v4
   - name: Print Message
     run: echo "Github Runner is working!"
